### ISSUE TITLE
Other projects with the same name: spotlight.js

### ISSUE THREAD

**Issue by kajmagnus** [alvaromontoro/TourGuide#27]
Hi, theres's this project:  https://github.com/bestiejs/spotlight.js and this: https://github.com/m1ci/SpotlightJS

Two other projects with the same name. This can cause confusion, if you'd like to publish this project to NPM?  People would most of the time intall the wrong lib? if they just type `npm install spotlightjs` apparently they'll install this instead: https://www.npmjs.com/package/SpotlightJS

What about renaming? SpotlightTour maybe?

B.t.w. this looks great :- ) Planning to have a closer look, and use in my project. I love it that this is lightweight.  All other tour libs, I don't want to use (except for https://github.com/callahanrts/tiny-tour/blob/master/src/tour.js, also lightweight), because they have too many features, too much code, would be a bit slow to load on mobile.

Such a good idea to do spots, via round and super wide border-radius 50%  :- )   (hmm looks like 100% in the CSS file. I think 50% is enough.)

**Comment by alvaromontoro** [comment]
Name updated to TourGuide.
