### ISSUE TITLE
Dual license under GPL v2? Maybe MIT?

### ISSUE THREAD

**Issue by kajmagnus** [alvaromontoro/TourGuide#28]
This project is licensed under GPL 3.  What about dual licensing it under GPL 2 and 3?  Or maybe change to  "GPL v2 or later"?  I'm looking to release a project under GPL 2.

Or  maybe MIT?  (Unless you specifically want this to be GPL?)

**Comment by alvaromontoro** [comment]
The project license was updated to MIT. 
Thanks for the suggestion, and sorry for the late reply.

**Comment by kajmagnus** [comment]
Thanks for the reply. (I've built my own tour lib now :- ))

**Comment by alvaromontoro** [comment]
Please share link, I'd love to see it. Maybe I could get some ideas from it too (if that's ok)

**Comment by kajmagnus** [comment]
@alvaromontoro  here: https://github.com/debiki/talkyard/blob/02f7ae55ed7f38a3c3c124168bf60f9e41be6e5c/client/app-slim/utils/talkyard-tour.ts  — I didn't yet take the time to extract this to its own lib. To see it in action, currently you'd need to create a Talkyard test site, https://www.talkyard.net/-/create-test-site, click " create a test forum".
