### ISSUE TITLE
Improve npm integration

### ISSUE THREAD

**Issue by alvaromontoro** [alvaromontoro/TourGuide#32]
Right now, when the project is built and published into npm, the whole project is submitted there. The goals of this ticket are to:

- Verify the npm publication.
- Make the needed adjustments so only what is needed is published.
- Clean the related code.

**Comment by dulcetti** [comment]
Hi, Alvaro. Can I get this issue?

**Comment by alvaromontoro** [comment]
Please do. Thanks for helping!

**Comment by alvaromontoro** [comment]
Fixed as part of #38
